### PR TITLE
Add ZMUB NON RADAR AREA

### PR DESCRIPTION
**Pull request by XCSWxcsw**
根据AIP Mongolia ENR 1.7的2.1.1b:"procedural control service is provided for Altai, Bayan sectors, as well as in non radar areas."
及航路图所标注的坐标 制作此分割线

### CODE REVIEW

**Comment by mic12130** [comment]
数据好像有问题
根据ENR2.1 CONTROL AREA，non radar area有且仅有最东侧的一小块，西侧的线应该是Altai sector，但是没有找到有关这块区域是non radar area的说明

Annotation 2020-03-10 101406

**Comment by mic12130** [comment]
也可以考虑把这个pr关掉，另开一个添加程序管制边界线的pr。因为上线管制时，程序管制的边界线要比non radar area的边界线更常用。

**只是建议**

**Comment by XCSWxcsw** [comment]
东侧为航路图标注 西侧俩扇区为AIP说明
2.1.1 Ulaanbaatar FIR’s 6 sectors: Central, Muren, Gobi, Dornod, Altai and Bayan are provided with radar and procedural air traffic control services.
radar control service is provided for Central, Muren, Dornod and Gobi sectors;
whereas, procedural control service is provided for Altai, Bayan sectors, as well as in non radar areas.

**Comment by mic12130** [comment]
`procedural control service is provided for Altai, Bayan sectors, as well as in non radar areas`

对啊，你画的西侧线是Altai和Bayan，东侧线是non radar area，然后这三块都是程序管制范围

没有说这三块全部是non radar area吧

**Comment by XCSWxcsw** [comment]
emmm！哦！雷达覆盖下的程序管制 好吧我错了 一会修

**Comment by mic12130** [comment]
另外注意一下数据里命名的大小写，应该改为Non Radar Area

**Comment by XCSWxcsw** [comment]
fixed

**Comment by mic12130** [comment]
ref #36

**Pull request merged**
